### ISSUE TITLE
add Event handling for uk-switcher component

### ISSUE THREAD

**Issue by stefanhofmann2** [adfinis-sygroup/ember-uikit#187]
is it possible to add the following code to the item sub-component of uk-switcher:
  setEvents() {
    let events = {
      beforeshow: this.getWithDefault("on-beforeshow", noop),
      show: this.getWithDefault("on-show", noop),
      shown: this.getWithDefault("on-shown", noop),
      beforehide: this.getWithDefault("on-beforehide", noop),
      hide: this.getWithDefault("on-hide", noop),
      hidden: this.getWithDefault("on-hidden", noop)
    };

    for (let event in events) {
      UIkit.util.on(this.element, event, events[event]);
    }
  },
  didInsertElement() {
    this._super(...arguments);
    this.setEvents();
  }
to enable the event handling. Thanks

**Comment by anehx** [comment]
Hi @stefanhofmann2 

Could you open a pull request with your suggested code?

**Comment by stefanhofmann2** [comment]
done

**Comment by anehx** [comment]
Actually, this was not exactly what I meant. I left you some feedback on [your PR](https://github.com/adfinis-sygroup/ember-uikit/pull/188) on how to do it properly..

**Comment by stefanhofmann2** [comment]
ok, is available in new release
