### ISSUE TITLE
@import dependencies failed

### ISSUE THREAD

**Issue by ronny35** [adfinis-sygroup/ember-uikit#245]
Hello,

I tried to install this package but transitive dependencies downloading like "ember-uikit/variable-themes" failed.

I use broccoli-sass to compile scss file which content :
@import "node_modules/ember-uikit/app/styles/ember-uikit.scss"

I would not use "ember-cli-sass" because I have already several transformations of css files in my Ember App.

Thanks for your help.

**Comment by anehx** [comment]
Hi @ronny35 

If you want to import UIkit specific styles such as `variables-theme` you'll have to directly import them from the UIkit package. `ember-uikit` enables importing them directly in the app by adding it to the styles tree.

Try importing `node_modules/uikit/src/scss/variables-theme.scss` instead!

**Comment by ronny35** [comment]
Hi @anehx 

Thanks for this response. I checked this config and it works!
But, if I use `ember-cli-sass`,  this config works fine `@import "ember-uikit"` and it is most useful than all single imports.

Do you have any ideas ?

Thanks.

**Comment by anehx** [comment]
Hi @ronny35 

I don't really understand what the problem is? Are you trying to include the full UIkit styles but without using `ember-cli-sass`?

**Comment by ronny35** [comment]
Yes, you're right.

**Comment by anehx** [comment]
If you don't have `ember-cli-sass` installed, `ember-uikit` will include the full UIkit styles per default:

https://github.com/adfinis-sygroup/ember-uikit/blob/master/index.js#L119-L122
