### ISSUE TITLE
Modal Support?

### ISSUE THREAD

**Issue by jayvarner** [adfinis-sygroup/ember-uikit#36]
Is anyone working on adding a uk-modal component? I have one I've been using that is more-or-less ready for review.

**Comment by anehx** [comment]
Hi,

Sadly we can't make progress on this addon at this moment since we are too busy with other projects. However, if you open a PR we'd love to review it!

Basically the goal of this addon is to cover all the components delivered by UIkit, so every PR implementing something is more than welcome.

**Comment by czosel** [comment]
This has been implemented in #81 👍
