### ISSUE TITLE
Page scrolls up on click anywhere

### ISSUE THREAD

**Issue by Yelinz** [adfinis-sygroup/ember-uikit#419]
When using a modal and having a scroll, under some circumstances when clicking anywhere the page will scroll to the top again. 

The issue seems to come from focus-trap, this is a issue with a similar problem
https://github.com/davidtheclark/focus-trap/issues/104 

Currently there is no released version of focus-trap with the fix, which could be used in ember-focus-trap, to potentially fix the scrolling problem.

**Comment by czosel** [comment]
@Yelinz did you try the bugfix which has landed in the `master` branch of focus-trap on december 2?

**Comment by Yelinz** [comment]
Yes and it works if you set the option, but as I said initially 

> Currently there is no released version of focus-trap with the fix

We also would need an new release in ember-focus-trap

**Comment by czosel** [comment]
:+1: Alright, thanks for the clarification :upside_down_face:

**Comment by anehx** [comment]
Fixed by #560
