### ISSUE TITLE
Recompile without sass changes

### ISSUE THREAD

**Issue by pomm0** [adfinis-sygroup/ember-uikit#778]
This addon forces a sass recompilation for any changes that happen while in ember server modus, even though no sass files changed.

### How to reproduce

1. create a new ember app
2. install ember-uikit `ember install ember-uikit`
3. start ember server
4. change something inside a `.js` file for instance `controller/application.js`
5. observe server logs and see that a SassCompiler did run:

![image](https://user-images.githubusercontent.com/6084030/140528453-3490b929-86cc-45e6-a120-41ec26a0c05d.png)

Since our app has quite lot to compile it adds 3-4 seconds of rebuild time everytime we change something not sass related. Which slows down productivity.
Is there something I can do to change it that it only recompiles when a scss file did change?

**Comment by anehx** [comment]
`ember-uikit` doesn't do any compilation, that is entirely handled by `ember-cli-sass` which currently does have the issue you're describing: https://github.com/adopted-ember-addons/ember-cli-sass/issues/214

I'll close this issue since SCSS compilation is not a concern of this addon.
