### ISSUE TITLE
can't build success in ember 3.9.0

### ISSUE THREAD

**Issue by jeffma** [adfinis-sygroup/ember-uikit#88]
ember-uikit\components\heading.scss:125:26

Error: expected selector.
    ╷
125 │ .uk-heading-primary when ($deprecated = true){

**Comment by Yelinz** [comment]
Should be fixed when #90 gets resolved.

**Comment by fkm** [comment]
Currently failing at https://github.com/adfinis-sygroup/ember-uikit/blob/master/tests/acceptance/index-test.js#L9

I wonder if I should just ignore it and merge anyway.

**Comment by fkm** [comment]
Merged

**Comment by jeffma** [comment]
build success, thanks
